// app/layout.tsx (Server Component)
import type { Metadata } from "next";
import RootLayout from "./rootLayout"; // Client component
import { ConvexClientProvider } from "../providers/convex_client_provider"; // Client component

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function Layout({ children }: { children: React.ReactNode }) {
  return (
    <ConvexClientProvider>
      <RootLayout>{children}</RootLayout>
    </ConvexClientProvider>
  );
}
