import type { Metadata } from "next";
import RootLayout from "./rootLayout";
import { ConvexClientProvider } from "../providers/convex_client_provider";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function Layout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className="antialiased">
        <ConvexClientProvider>
          <RootLayout>{children}</RootLayout>
        </ConvexClientProvider>
      </body>
    </html>
  );
}
